# Wstęp i cel badań {.unnumbered}

Praca naukowa to określony rodzaj formy pracy twórczej związany z obiektywnym poznaniem zjawisk, rzeczy oraz różnego rodzaju relacji pomiędzy nimi. 

Wyniki prac badawczych przedstawia się w rożnych formach (książki, raporty,czy sprawozdania) ale najbardziej popularną metodą jest pisanie artykułów naukowych.

Artykuły naukowe zamieszczane są w czasopismach, które publikują je w formie papierowej lub najczęściej elektronicznej przez wydawnictwa naukowe. Ocena wpływu danych czasopism odbywa się poprzez analizę bibliometryczną cytowań, gdzie liczba cytowań artykułów w czasopiśmie stanowi miarę popularności i wpływu czasopisma. 

Naukowcy także podlegają ewaluacji miedzy innymi poprzez systematyczną ocenę ich dorobku naukowego. Dorobek ten wyceniany jest miedzy innymi w oparciu o opublikowane artykuły naukowe w czasopismach oraz ilość cytowań, jakie ten artykuł otrzymał.

W związku z powyższym obserwuje się ścisłe wzajemne relacje pomiędzy naukowcami a wydawnictwami czasopism. Przyczynia się to do powstania ogromnej ilości artykułów naukowych, które są indeksowane w tematycznych bazach danych.

## Cel badań:

Znaczący przyrost ilości artykułów w danych dyscyplinach naukowych nasilają problemy z ich przeglądem i oceną. Wykonywanie takich przeglądów standardowymi "ręcznymi" metodami jest coraz bardziej czasochłonne i mało efektywne.
Celem badan było wykonanie przeglądu oraz meta-analizy danych literatury naukowej metodami opartymi o data science, które umożliwiłyby ten etap pracy naukowej znacznie przyspieszyć i zwiększyć jego efektywność.



