---
output: pdf_document
---

# Wstęp i cel badań\label{label1}

Praca naukowa to określony rodzaj formy pracy twórczej związany z obiektywnym poznaniem zjawisk, rzeczy oraz różnego rodzaju relacji pomiędzy nimi. Wyniki prac naukowych przedstawia się w rożnych formach (książki, raporty, czy sprawozdania) spośród których, najbardziej popularną metodą jest pisanie artykułów (publikacji) naukowych.

**Publikację naukową** można zdefiniować w różny sposób w zależności od celu w jakim została stworzona. Najogólniej publikacją naukową określa się doniesienie o uzyskanych wynikach badań lub opis istniejącego stanu wiedzy z określonego obszaru nauki. Artykuły naukowe zamieszczane są w czasopismach, które publikują je w formie papierowej lub najczęściej elektronicznej przez wydawnictwa naukowe. Ocena wpływu danych czasopism odbywa się poprzez analizę bibliometryczną cytowań, gdzie liczba cytowań artykułów w czasopiśmie stanowi miarę popularności i wpływu czasopisma. Większość wydawnictw publikujących prace naukowe wykorzystuje własne strony internetowe do przyjmowania, recenzowania oraz udostępniania publikowanych prac w trybie on-line.

Naukowcy także podlegają ewaluacji miedzy innymi poprzez systematyczną ocenę ich dorobku naukowego. Dorobek ten wyceniany jest miedzy innymi w oparciu o opublikowane artykuły naukowe w czasopismach oraz ilość cytowań, jakie ten artykuł otrzymał. Ilość i jakość opublikowanych prac naukowych jest istotna dla pracowników jak i dla instytucji naukowych w której są zatrudnieni, ponieważ zarówno te podmioty jak również pracownicy w nich zatrudnieni podlegają okresowej ocenie. Ewaluację przeprowadza się za okres 4 lat poprzedzających rok jej przeprowadzenia, z uwzględnieniem osiągnięć naukowych pracowników [@dz.u.2019]. W związku z powyższym obserwuje się ścisłe wzajemne relacje pomiędzy naukowcami a wydawnictwami czasopism. Przyczynia się to do powstania dużej ilości artykułów naukowych, które są indeksowane w tematycznych bazach danych.

**Cel badań:** znaczący przyrost ilości artykułów w danych dyscyplinach naukowych nasilają problemy z ich przeglądem i oceną. Wykonywanie takich przeglądów standardowymi "ręcznymi" metodami jest coraz bardziej czasochłonne i mało efektywne. Celem badan było wykonanie przeglądu bibliograficznego literatury naukowej metodami opartymi o narzędzia data science. Hipotezy badawcza projektu zakłada, że metody data science przyspieszają i zwiększając efektywność przeprowadzenia przeglądu bibliograficznego w porównaniu z tradycyjnymi metodami jego wykonania.
