---
output:
  pdf_document:
    keep_tex: true
    fig_caption: yes
    number_sections: yes
  html_document:
    df_print: paged
  word_document: default
bibliography: references.bib
link-citations: TRUE
csl: Literatura/Style/agronomy-journal.csl
lang: pl-PL
urlcolor: blue
linkcolor: blue
fontsize: 12pt
geometry: margin = 1.2in
suppress-bibliography: false
zotero: true
header-includes:
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage[document]{ragged2e}
- \usepackage{float}
- \floatplacement{figure}{H}
- \usepackage[all]{nowidow}
- \usepackage{placeins}                   #https://polish-mirror.evolution-host.com/ctan/macros/latex/contrib/placeins/placeins-doc.pdf
- \usepackage{fancyhdr}                   #https://ctan.gust.org.pl/tex-archive/macros/latex/contrib/fancyhdr/fancyhdr.pdf
- \usepackage{setspace}                   #https://www.ctan.org/pkg/setspace
- \onehalfspacing                         #http://kb.mit.edu/confluence/pages/viewpage.action?pageId=3907092
- \usepackage{chngcntr}                   #https://sunsite.icm.edu.pl/pub/CTAN/macros/latex/contrib/chngcntr/chngcntr.pdf
- \usepackage{microtype}                  #https://polish-mirror.evolution-host.com/ctan/macros/latex/contrib/microtype/microtype.pdf
---

\def\figurename{Rysunek}

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.path = 'Rysunki/figures/', echo = FALSE, warning = FALSE, message = FALSE)
library(rbbt)

```

```{r child = '01_tytul.Rmd'}
```

```{=tex}
\newpage
\pagestyle{fancy}
```
```{=tex}
\fancyhead[L,R]{}
\fancyhead[L,R]{}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0pt}
```
```{=tex}
\fancyhead[C]{Streszczenie}
\section*{Streszczenie}
\addcontentsline{toc}{section}{Streszczenie}
\justify
```
```{r child = '02_streszczenie.Rmd'}
```

```{=tex}
\newpage
\fancyhead[C]{Podziękowania}
\section*{Podziękowania}
```
```{r child = '03_podziekowania.Rmd'}
```


```{=tex}
\newpage
\fancyhead[C]{Spis treści}
\setcounter{tocdepth}{2}
\tableofcontents
\addcontentsline{toc}{section}{Spis treści}
```
\newpage

```{=tex}
\newpage
\fancyhead[C]{Wstęp i określenie celu badań}
```
```{r child = '04_wstep_cel_badan.Rmd'}

```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Opis problemu badań}
```
```{r child = '05_opis_problemu_badan.Rmd'}

```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Metodyka badań}
```
```{r child = '06_metodyka_badan.Rmd'}
```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Wyniki badań i dyskusja}
```
```{r child = '07_wyniki_badan_dyskusja.Rmd'}

```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Wnioski}
```
```{r child = '08_wnioski.Rmd'}
```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Literatura}
```
# Literatura

::: {#refs}
:::

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Spis rysunków}
\listoffigures
\addcontentsline{toc}{section}{Spis rysunków}
```
```{=tex}
\newpage
\pagestyle{plain}
```
```{r child = '09_oswiadczenie.Rmd'}
```

```{=tex}
\FloatBarrier
\newpage
\fancyhead[C]{Test}
```
```{r child = '10_Test.Rmd'}
```

