---
output: pdf_document

---

# Test\label{label1}


```{r echo=TRUE}

# library(reticulate)
# 
# # Import and run a Python file
# py_run_file("Skrypty/test_skryptu.py")

```

Przykład wyszukania tytułu publikacji poprzez jej DOI (Digital Object Identifier), czyli unikalny identyfikator:

```{python echo=TRUE}

# from semanticscholar import SemanticScholar
# sch = SemanticScholar()
# paper = sch.get_paper('10.1016/j.jafr.2024.101013')
# paper.title

```

Przykład wyszukania autora publikacji poprzez jego numer identyfikujący:

```{python}

from semanticscholar import SemanticScholar
sch = SemanticScholar()
author = sch.get_author(113275711)
author.name

```

Wyszukanie autora publikacji poprzez jego dane Imię i Nazwisko:

```{python}
from semanticscholar import SemanticScholar
sch = SemanticScholar()
results = sch.search_author('Grzegorz Kulczycki')
print(f'{results.total} results.', f'First occurrence: {results[0].name}.')


```







```{r echo=TRUE}

# library(tidyjson) 
# library(dplyr)
# json_data <- jsonlite::fromJSON("JSON/response.json") 
# df <- as.data.frame(json_data) 
# formatted_df <- format(df, justify = "left")
# head(formatted_df, right = FALSE)

```









